# POST http://localhost:3003/api/login
# Content-Type: application/json

# {
# 	"username": "ayomide",
# 	"password": "secret123"
# }



DELETE http://localhost:3003/api/blogs/6ab356938ea13229b1fb35d1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImF5b21pZGUiLCJpZCI6IjZhYjM1NjI4OGVhMTMyMjliMWZiMzVjZSIsImlhdCI6MTc5MDIyNzA1OX0.AV8mWd6sByzwOPLEmYBYYaeDPhVxCyK_Un04gWwlc6I

 